"""empty message

Revision ID: 443a3b413209
Revises: 336e5d8679be
Create Date: 2024-07-14 15:04:29.321689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443a3b413209'
down_revision: Union[str, None] = '336e5d8679be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('cartegorias')
    op.add_column('atletas', sa.Column('nome_time', sa.String(length=50), nullable=False))
    op.add_column('atletas', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.drop_constraint('atletas_cartegoria_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    op.drop_column('atletas', 'cartegoria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('cartegoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_cartegoria_id_fkey', 'atletas', 'cartegorias', ['cartegoria_id'], ['pk_id'])
    op.drop_column('atletas', 'categoria_id')
    op.drop_column('atletas', 'nome_time')
    op.create_table('cartegorias',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name='cartegorias_pkey'),
    sa.UniqueConstraint('nome', name='cartegorias_nome_key')
    )
    op.drop_table('categorias')
    # ### end Alembic commands ###
